//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTalkEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTalkEdit.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 The file assets are the image and sound files used in the scenes, including the background and characters. The images of characters with transparency are called &quot;sprites&quot;. Each sprites and sounds are placed in the same directory, assigned unique IDs, and exported to image and audio HTML elements in the result web pages. 的當地語系化字串。
        /// </summary>
        internal static string helpFileAssets {
            get {
                return ResourceManager.GetString("helpFileAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The label of frame consists of alphabets, numbers, and underline. It sets up a jumpping target for for path options. It is also the tag for remembering the option the the user selected. For a frame that simply goes to the next frame, it is optional. For a frame the contains path options or wanna be a option of other frames, it is required. 的當地語系化字串。
        /// </summary>
        internal static string helpFrameLabel {
            get {
                return ResourceManager.GetString("helpFrameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a folder as the current working directory. Every sub-directory that contains a xtalk.proj file is listed as a script project. If the related CSS, Images, Scripts files are not found, it prepares for you. 的當地語系化字串。
        /// </summary>
        internal static string helpSelectWorkDirectory {
            get {
                return ResourceManager.GetString("helpSelectWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preview unavailable! 的當地語系化字串。
        /// </summary>
        internal static string msgBlankHtml {
            get {
                return ResourceManager.GetString("msgBlankHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} frame(s)  copied. 的當地語系化字串。
        /// </summary>
        internal static string msgFramesCopied {
            get {
                return ResourceManager.GetString("msgFramesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a new unique ID that is recommended to consist of alphabets, numbers, and underline. 的當地語系化字串。
        /// </summary>
        internal static string msgNewID {
            get {
                return ResourceManager.GetString("msgNewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a unique ID for the newly added file. It is recommended to consist of alphabets, numbers, and underline. 的當地語系化字串。
        /// </summary>
        internal static string msgNewIDforFile {
            get {
                return ResourceManager.GetString("msgNewIDforFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a new project name as the newly created sub-directory in the current working directory. 的當地語系化字串。
        /// </summary>
        internal static string msgNewProjectName {
            get {
                return ResourceManager.GetString("msgNewProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a new scene script name. It will be the file title of newly created .xtalk file in the current project directory. 的當地語系化字串。
        /// </summary>
        internal static string msgNewSceneName {
            get {
                return ResourceManager.GetString("msgNewSceneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No more frames found. 的當地語系化字串。
        /// </summary>
        internal static string msgNoMoreFrames {
            get {
                return ResourceManager.GetString("msgNoMoreFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not implemented yet! 的當地語系化字串。
        /// </summary>
        internal static string msgNotImplemented {
            get {
                return ResourceManager.GetString("msgNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Please input the option text) 的當地語系化字串。
        /// </summary>
        internal static string msgPleaseInputOptText {
            get {
                return ResourceManager.GetString("msgPleaseInputOptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter a new scene name which should not be the same with another scene in the project. 的當地語系化字串。
        /// </summary>
        internal static string msgRenameScene {
            get {
                return ResourceManager.GetString("msgRenameScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The inputted value can not be blank! 的當地語系化字串。
        /// </summary>
        internal static string warnBlankNotAllowed {
            get {
                return ResourceManager.GetString("warnBlankNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The file already exists. 的當地語系化字串。
        /// </summary>
        internal static string warnFileAlreadyExists {
            get {
                return ResourceManager.GetString("warnFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to delete this item? 的當地語系化字串。
        /// </summary>
        internal static string warnRUSureToDelete {
            get {
                return ResourceManager.GetString("warnRUSureToDelete", resourceCulture);
            }
        }
    }
}
