//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTalkEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTalkEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Asset Files 的當地語系化字串。
        /// </summary>
        public static string AssetFiles {
            get {
                return ResourceManager.GetString("AssetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Background 的當地語系化字串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Background Images 的當地語系化字串。
        /// </summary>
        public static string BackgroundImgs {
            get {
                return ResourceManager.GetString("BackgroundImgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Blur 的當地語系化字串。
        /// </summary>
        public static string Blur {
            get {
                return ResourceManager.GetString("Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Continue 的當地語系化字串。
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy 的當地語系化字串。
        /// </summary>
        public static string BtnCopy {
            get {
                return ResourceManager.GetString("BtnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Duplicate 的當地語系化字串。
        /// </summary>
        public static string BtnDuplicate {
            get {
                return ResourceManager.GetString("BtnDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Export and Play 的當地語系化字串。
        /// </summary>
        public static string BtnExpAndPlay {
            get {
                return ResourceManager.GetString("BtnExpAndPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Import from a file... 的當地語系化字串。
        /// </summary>
        public static string BtnImport {
            get {
                return ResourceManager.GetString("BtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New 的當地語系化字串。
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        public static string BtnOK {
            get {
                return ResourceManager.GetString("BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Output to Files 的當地語系化字串。
        /// </summary>
        public static string BtnOutputToFile {
            get {
                return ResourceManager.GetString("BtnOutputToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paste 的當地語系化字串。
        /// </summary>
        public static string BtnPaste {
            get {
                return ResourceManager.GetString("BtnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove 的當地語系化字串。
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rename 的當地語系化字串。
        /// </summary>
        public static string BtnRename {
            get {
                return ResourceManager.GetString("BtnRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select... 的當地語系化字串。
        /// </summary>
        public static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Center Char 的當地語系化字串。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dialog of Characters 的當地語系化字串。
        /// </summary>
        public static string CharDialog {
            get {
                return ResourceManager.GetString("CharDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cover Page 的當地語系化字串。
        /// </summary>
        public static string CoverPage {
            get {
                return ResourceManager.GetString("CoverPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Darken 的當地語系化字串。
        /// </summary>
        public static string Darken {
            get {
                return ResourceManager.GetString("Darken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Frame Composition 的當地語系化字串。
        /// </summary>
        public static string FrameComp {
            get {
                return ResourceManager.GetString("FrameComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sounds of Frames 的當地語系化字串。
        /// </summary>
        public static string FrameSounds {
            get {
                return ResourceManager.GetString("FrameSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test the Frame 的當地語系化字串。
        /// </summary>
        public static string FrameTest {
            get {
                return ResourceManager.GetString("FrameTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Frame Type 的當地語系化字串。
        /// </summary>
        public static string FrameType {
            get {
                return ResourceManager.GetString("FrameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Frame Type and Path 的當地語系化字串。
        /// </summary>
        public static string FrameTypeAndPath {
            get {
                return ResourceManager.GetString("FrameTypeAndPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Full-Screen Text 的當地語系化字串。
        /// </summary>
        public static string FullScrText {
            get {
                return ResourceManager.GetString("FullScrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Goto 的當地語系化字串。
        /// </summary>
        public static string Goto {
            get {
                return ResourceManager.GetString("Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Height 的當地語系化字串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Popup 的當地語系化字串。
        /// </summary>
        public static string HrefBlank {
            get {
                return ResourceManager.GetString("HrefBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Default 的當地語系化字串。
        /// </summary>
        public static string HrefSelf {
            get {
                return ResourceManager.GetString("HrefSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Full Page 的當地語系化字串。
        /// </summary>
        public static string HrefTop {
            get {
                return ResourceManager.GetString("HrefTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Label 的當地語系化字串。
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Left #1 Char 的當地語系化字串。
        /// </summary>
        public static string Left1 {
            get {
                return ResourceManager.GetString("Left1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Left #2 Char 的當地語系化字串。
        /// </summary>
        public static string Left2 {
            get {
                return ResourceManager.GetString("Left2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;Next&quot; Button 的當地語系化字串。
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next Frame 的當地語系化字串。
        /// </summary>
        public static string NextFrame {
            get {
                return ResourceManager.GetString("NextFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (None) 的當地語系化字串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original Frame Size 的當地語系化字串。
        /// </summary>
        public static string OrigFrameSize {
            get {
                return ResourceManager.GetString("OrigFrameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Output JavaScript and HTML 的當地語系化字串。
        /// </summary>
        public static string OutputJsHtml {
            get {
                return ResourceManager.GetString("OutputJsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GET Options 的當地語系化字串。
        /// </summary>
        public static string PackOpts {
            get {
                return ResourceManager.GetString("PackOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Carry the path choices as URL GET parameters. 的當地語系化字串。
        /// </summary>
        public static string PackOptsMsg {
            get {
                return ResourceManager.GetString("PackOptsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Path Options 的當地語系化字串。
        /// </summary>
        public static string PathOptions {
            get {
                return ResourceManager.GetString("PathOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preview 的當地語系化字串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preview the Image 的當地語系化字串。
        /// </summary>
        public static string PreviewImg {
            get {
                return ResourceManager.GetString("PreviewImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Right #1 Char 的當地語系化字串。
        /// </summary>
        public static string Right1 {
            get {
                return ResourceManager.GetString("Right1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Right #2 Char 的當地語系化字串。
        /// </summary>
        public static string Right2 {
            get {
                return ResourceManager.GetString("Right2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scenes and Scripts 的當地語系化字串。
        /// </summary>
        public static string SceneScript {
            get {
                return ResourceManager.GetString("SceneScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Script Projects 的當地語系化字串。
        /// </summary>
        public static string ScriptProject {
            get {
                return ResourceManager.GetString("ScriptProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search the frame that contains the text: 的當地語系化字串。
        /// </summary>
        public static string SeachFrameText {
            get {
                return ResourceManager.GetString("SeachFrameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Please select a directory...) 的當地語系化字串。
        /// </summary>
        public static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sound Effect 的當地語系化字串。
        /// </summary>
        public static string SoundEffect {
            get {
                return ResourceManager.GetString("SoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Speaker 的當地語系化字串。
        /// </summary>
        public static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Character Sprites 的當地語系化字串。
        /// </summary>
        public static string SpriteImgs {
            get {
                return ResourceManager.GetString("SpriteImgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text Content 的當地語系化字串。
        /// </summary>
        public static string TextContent {
            get {
                return ResourceManager.GetString("TextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Text Options 的當地語系化字串。
        /// </summary>
        public static string TextOptions {
            get {
                return ResourceManager.GetString("TextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value 的當地語系化字串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Web 的當地語系化字串。
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Width 的當地語系化字串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Working Directory 的當地語系化字串。
        /// </summary>
        public static string WorkDirectory {
            get {
                return ResourceManager.GetString("WorkDirectory", resourceCulture);
            }
        }
    }
}
